FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
        ansible \
        docker.io \
        python3 \
        python3-pip  \
        openssh-client \
        openssh-server \
        sshpass \
        git \
        openjdk-17-jdk \
        sshpass && \
    apt-get clean

WORKDIR /ansible

RUN mkdir /var/run/sshd

RUN echo 'root:root' | chpasswd

RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config

EXPOSE 22


CMD ["/usr/sbin/sshd", "-D"]