FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
        ansible \
        docker.io \
        python3 \
        python3-pip  \
        openssh-client \
        sshpass && \
    apt-get clean

WORKDIR /ansible

RUN mkdir /var/run/sshd

RUN echo 'root:root' | chpasswd

EXPOSE 22

CMD ["bash"]