---
name: Lint Code

"on":
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Download Repo
        uses: actions/checkout@v4

      - name: Install yamllint
        run: pip install yamllint

      - name: Exec lint
        run: yamllint .
        